#include "stdafxClient.h"
#include "PacketHandler.h"
#include "NetworkGlobal.h"
#include "PacketEnums.h"
#include "Packets/S2CPackets.h"

#define REGISTER_PACKET(PACKET_ENUM, FB_TABLE, HANDLER_FUNC) RegisterPacketHandler<FB_TABLE, HANDLER_FUNC>(PACKET_ENUM)

using namespace NetBridge;

void NetBridge::PacketHandler::Init()
{
	for (auto& packetHandlerFunc : m_packetHandlerFuncs)
		packetHandlerFunc = S2C::Handle_Invalid;

	RegisterHandlers();
}

void NetBridge::PacketHandler::RegisterPacketHandler(
	PACKET_TYPE packetType, PacketHandlerFunc packetHandlerFunc
) noexcept
{
	m_packetHandlerFuncs[static_cast<uint16>(packetType)] = packetHandlerFunc;
}

void NetBridge::LobbyServerPacketHandler::RegisterHandlers() noexcept
{
#pragma region LOGIN_PACKETS
	REGISTER_PACKET(PACKET_TYPE::LC_LOGIN_FAIL_PKT, FB_TABLES::LC_LOGIN_FAIL_PACKET, S2C::Handle_LC_LOGIN_FAIL_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_LOGIN_SUCCESS_PKT, FB_TABLES::LC_LOGIN_SUCCESS_PACKET, S2C::Handle_LC_LOGIN_SUCCESS_PACKET);
	REGISTER_PACKET(
		PACKET_TYPE::LC_SIGN_UP_FAIL_PKT, FB_TABLES::LC_SIGN_UP_FAIL_PACKET, S2C::Handle_LC_SIGN_UP_FAIL_PACKET
	);
	REGISTER_PACKET(
		PACKET_TYPE::LC_SIGN_UP_SUCCESS_PKT, FB_TABLES::LC_SIGN_UP_SUCCESS_PACKET, S2C::Handle_LC_SIGN_UP_SUCCESS_PACKET
	);
	
#pragma endregion

#pragma region LOBBY_PACKETS
	REGISTER_PACKET(PACKET_TYPE::LC_ENTER_GAME_LOBBY_FAIL_PKT, FB_TABLES::LC_ENTER_GAME_LOBBY_FAIL_PACKET, S2C::Handle_LC_ENTER_GAME_LOBBY_FAIL_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_ENTER_GAME_LOBBY_SUCCESS_PKT, FB_TABLES::LC_ENTER_GAME_LOBBY_SUCCESS_PACKET, S2C::Handle_LC_ENTER_GAME_LOBBY_SUCCESS_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_LEAVE_GAME_LOBBY_PKT, FB_TABLES::LC_LEAVE_GAME_LOBBY_PACKET, S2C::Handle_LC_LEAVE_GAME_LOBBY_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_ENTER_USER_IN_GAME_LOBBY_PKT, FB_TABLES::LC_ENTER_USER_IN_GAME_LOBBY_PACKET, S2C::Handle_LC_ENTER_USER_IN_GAME_LOBBY_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_LEAVE_USER_IN_GAME_LOBBY_PKT, FB_TABLES::LC_LEAVE_USER_IN_GAME_LOBBY_PACKET, S2C::Handle_LC_LEAVE_USER_IN_GAME_LOBBY_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_MAKE_GAME_ROOM_PKT, FB_TABLES::LC_MAKE_GAME_ROOM_PACKET, S2C::Handle_LC_MAKE_GAME_ROOM_PACKET);
#pragma endregion

#pragma region ROOM_PACKETS
	REGISTER_PACKET(PACKET_TYPE::LC_ENTER_GAME_ROOM_FAIL_PKT, FB_TABLES::LC_ENTER_GAME_ROOM_FAIL_PACKET, S2C::Handle_LC_ENTER_GAME_ROOM_FAIL_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_ENTER_GAME_ROOM_SUCCESS_PKT, FB_TABLES::LC_ENTER_GAME_ROOM_SUCCESS_PACKET, S2C::Handle_LC_ENTER_GAME_ROOM_SUCCESS_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_LEAVE_GAME_ROOM_PKT, FB_TABLES::LC_LEAVE_GAME_ROOM_PACKET, S2C::Handle_LC_LEAVE_GAME_ROOM_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_JOIN_PARTICIPANT_IN_GAME_ROOM_PKT, FB_TABLES::LC_JOIN_PARTICIPANT_IN_GAME_ROOM_PACKET, S2C::Handle_LC_JOIN_PARTICIPANT_IN_GAME_ROOM_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_LEAVE_PARTICIPANT_IN_GAME_ROOM_PKT, FB_TABLES::LC_LEAVE_PARTICIPANT_IN_GAME_ROOM_PACKET, S2C::Handle_LC_LEAVE_PARTICIPANT_IN_GAME_ROOM_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_CHANGE_TEAM_PKT, FB_TABLES::LC_CHANGE_TEAM_PACKET, S2C::Handle_LC_CHANGE_TEAM_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_ADD_BOT_PKT, FB_TABLES::LC_ADD_BOT_PACKET, S2C::Handle_LC_ADD_BOT_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_REMOVE_BOT_PKT, FB_TABLES::LC_REMOVE_BOT_PACKET, S2C::Handle_LC_REMOVE_BOT_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_READY_GAME_PKT, FB_TABLES::LC_READY_GAME_PACKET, S2C::Handle_LC_READY_GAME_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_START_GAME_FAIL_PKT, FB_TABLES::LC_START_GAME_FAIL_PACKET, S2C::Handle_LC_START_GAME_FAIL_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_CONNECT_TO_GAME_SERVER_PKT, FB_TABLES::LC_CONNECT_TO_GAME_SERVER_PACKET, S2C::Handle_LC_CONNECT_TO_GAME_SERVER_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_RETURN_TO_GAME_ROOM_PKT, FB_TABLES::LC_RETURN_TO_GAME_ROOM_PACKET, S2C::Handle_LC_RETURN_TO_GAME_ROOM_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_CHAT_PKT, FB_TABLES::LC_CHAT_PACKET, S2C::Handle_LC_CHAT_PACKET);
	REGISTER_PACKET(PACKET_TYPE::LC_GAME_RESULT_PKT, FB_TABLES::LC_GAME_RESULT_PACKET, S2C::Handle_LC_GAME_RESULT_PACKET);
#pragma endregion
}

void NetBridge::GameServerPacketHandler::RegisterHandlers() noexcept
{
#pragma region WORLD_PACKETS
	REGISTER_PACKET(PACKET_TYPE::SC_LOCAL_PLAYER_PKT, FB_TABLES::SC_LOCAL_PLAYER_PACKET, S2C::Handle_SC_LOCAL_PLAYER_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_ADD_OBJ_IN_GAME_WORLD_PKT, FB_TABLES::SC_ADD_OBJ_PACKET, S2C::Handle_SC_ADD_OBJ_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_REMOVE_OBJ_IN_GAME_WORLD_PKT, FB_TABLES::SC_REMOVE_OBJ_PACKET, S2C::Handle_SC_REMOVE_OBJ_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_MOVE_PKT, FB_TABLES::SC_MOVE_PACKET, S2C::Handle_SC_MOVE_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_GENERAL_ATTACK_PKT, FB_TABLES::SC_GENERAL_ATTACK_PACKET, S2C::Handle_SC_GENERAL_ATTACK_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_UPDATE_VITAL_PKT, FB_TABLES::SC_UPDATE_VITAL_PACKET, S2C::Handle_SC_UPDATE_VITAL_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_CHANGE_GENERAL_STANCE_PKT, FB_TABLES::SC_CHANGE_GENERAL_STANCE_PACKET, S2C::Handle_SC_CHANGE_GENERAL_STANCE_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_UPDATE_STATE_PKT, FB_TABLES::SC_UPDATE_STATE_PACKET, S2C::Handle_SC_UPDATE_STATE_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_REMAINING_GAME_TIME_PKT, FB_TABLES::SC_REMAINING_GAME_TIME, S2C::Handle_SC_REMAINING_GAME_TIME_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_CHANGE_CAMERA_TARGET_PKT, FB_TABLES::SC_CHANGE_CAMERA_TARGET_PACKET, S2C::Handle_SC_CHANGE_CAMERA_TARGET_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_CHANGE_GENERAL_ATTACK_DIR_PKT, FB_TABLES::SC_CHANGE_GENERAL_ATTACK_DIR_PACKET, S2C::Handle_SC_CHANGE_GENERAL_ATTACK_DIR_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_RESPAWN_GENERAL_PKT, FB_TABLES::SC_RESPAWN_GENERAL_PACKET, S2C::Handle_SC_RESPAWN_GENERAL_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_PING_PKT, FB_TABLES::SC_PING_PACKET, S2C::Handle_SC_PING_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_UPDATE_TEAM_SCORE_PKT, FB_TABLES::SC_UPDATE_TEAM_SCORE_PACKET, S2C::Handle_SC_UPDATE_TEAM_SCORE_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_OCCUPATION_ZONE_GAUGE_PKT, FB_TABLES::SC_OCCUPATION_ZONE_GAUGE_PACKET, S2C::Handle_SC_OCCUPATION_ZONE_GAUGE_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_OCCUPATION_ZONE_OCCUPIED_PKT, FB_TABLES::SC_OCCUPATION_ZONE_OCCUPIED_PACKET, S2C::Handle_SC_OCCUPATION_ZONE_OCCUPIED_PACKET);
	REGISTER_PACKET(PACKET_TYPE::SC_SOLDIER_ATTACK_PKT, FB_TABLES::SC_SOLDIER_ATTACK_PACKET, S2C::Handle_SC_SOLDIER_ATTACK_PACKET);
#pragma endregion

#pragma region TEST_PACKETS
	REGISTER_PACKET(PACKET_TYPE::SC_TELEPORT_PKT, FB_TABLES::SC_TELEPORT_PACKET, S2C::Handle_SC_TELEPORT_PACKET);
#pragma endregion
}

std::shared_ptr<NetBridge::PacketBuffer> NetBridge::PacketHandler::MakePacketBuffer(
	const PACKET_TYPE packetType, const flatbuffers::DetachedBuffer& packetData
)
{
	const uint16  packetSize = static_cast<uint16>(sizeof(PacketHeader) + (packetData.size()));
	auto		  packetBuffer = std::make_shared<NetBridge::PacketBuffer>(packetSize);
	PacketHeader* header = reinterpret_cast<PacketHeader*>(packetBuffer->GetBuffer());
	header->packetType = static_cast<uint16>(packetType);
	header->packetSize = packetSize;
	memcpy_s(&header[1], packetBuffer->GetCapacity() - sizeof(PacketHeader), packetData.data(), packetData.size());
	return packetBuffer;
}
