#pragma once

enum RIO_FIGURE {
	MAX_RIO_BUFFER_SIZE = 65536,	// 64kb
	MAX_RIO_BUFFER_COUNT = 2,

	MAX_RIO_BUFFER_CAPACITY = MAX_RIO_BUFFER_SIZE * MAX_RIO_BUFFER_COUNT,	
	
	MAX_RIO_RESULT = 256,
	MAX_SEND_RQ_SIZE_PER_SOCKET = 64,
	MAX_RECV_RQ_SIZE_PER_SOCKET = 64,
	MAX_SESION_PER_RIO_WORKER = 50,
	MAX_CQ_SIZE_PER_RIO_THREAD = (MAX_SEND_RQ_SIZE_PER_SOCKET + MAX_RECV_RQ_SIZE_PER_SOCKET) * MAX_SESION_PER_RIO_WORKER,

	SEND_LIMIT_SIZE = 600,
	COMMIT_TIME_MS_LIMIT = 20,
	MAX_POST_CNT = 256,
};

enum class SESSION_STATE : uint8 {
	FREE,		// Session 생성/소멸 
	ALLOC,		// Accept 직후 
	IN_GAME,	// 클라로부터 로그인 패킷 받았을 때
};