#pragma once

enum RIO_FIGURE {
	MAX_RIO_BUFFER_SIZE = 65536,
	MAX_RIO_BUFFER_COUNT = 2,

	MAX_RIO_BUFFER_CAPACITY = MAX_RIO_BUFFER_SIZE * MAX_RIO_BUFFER_COUNT,	
	
	MAX_RIO_RESULT = 256,
	MAX_SEND_RQ_SIZE_PER_SOCKET = 32,
	MAX_RECV_RQ_SIZE_PER_SOCKET = 32,
	MAX_CLIENT_PER_RIO_WORKER = 50,
	MAX_CQ_SIZE_PER_RIO_THREAD = (MAX_SEND_RQ_SIZE_PER_SOCKET + MAX_RECV_RQ_SIZE_PER_SOCKET) * MAX_CLIENT_PER_RIO_WORKER,
};