// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TABLES_FB_TABLES_H_
#define FLATBUFFERS_GENERATED_TABLES_FB_TABLES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "Enums_generated.h"
#include "Structs_generated.h"

namespace FB_TABLES {

struct CS_LOGIN_PACKET;
struct CS_LOGIN_PACKETBuilder;

struct SC_LOGIN_PACKET;
struct SC_LOGIN_PACKETBuilder;

struct CS_ENTER_ROOM_PACKET;
struct CS_ENTER_ROOM_PACKETBuilder;

struct SC_ENTER_ROOM_PACKET;
struct SC_ENTER_ROOM_PACKETBuilder;

struct SC_LOCAL_PLAYER_PACKET;
struct SC_LOCAL_PLAYER_PACKETBuilder;

struct SC_ADD_OBJ_PACKET;
struct SC_ADD_OBJ_PACKETBuilder;

struct SC_REMOVE_OBJ_PACKET;
struct SC_REMOVE_OBJ_PACKETBuilder;

struct CS_CHAT_PACKET;
struct CS_CHAT_PACKETBuilder;

struct SC_CHAT_PACKET;
struct SC_CHAT_PACKETBuilder;

struct CS_MOVE_PACKET;
struct CS_MOVE_PACKETBuilder;

struct SC_MOVE_PACKET;
struct SC_MOVE_PACKETBuilder;

struct CS_SUMMON_NPC;
struct CS_SUMMON_NPCBuilder;

struct CS_SOLDIER_FORMATION;
struct CS_SOLDIER_FORMATIONBuilder;

struct CS_PLAYER_ATTACK;
struct CS_PLAYER_ATTACKBuilder;

struct SC_HIT_PACKET;
struct SC_HIT_PACKETBuilder;

struct CS_SOLDIER_MOVE;
struct CS_SOLDIER_MOVEBuilder;

struct SC_REMAINING_GAME_TIME;
struct SC_REMAINING_GAME_TIMEBuilder;

struct CS_LOGIN_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CS_LOGIN_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_PW = 6
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *pw() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PW);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_PW) &&
           verifier.VerifyString(pw()) &&
           verifier.EndTable();
  }
};

struct CS_LOGIN_PACKETBuilder {
  typedef CS_LOGIN_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(CS_LOGIN_PACKET::VT_ID, id);
  }
  void add_pw(::flatbuffers::Offset<::flatbuffers::String> pw) {
    fbb_.AddOffset(CS_LOGIN_PACKET::VT_PW, pw);
  }
  explicit CS_LOGIN_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CS_LOGIN_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CS_LOGIN_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CS_LOGIN_PACKET> CreateCS_LOGIN_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> pw = 0) {
  CS_LOGIN_PACKETBuilder builder_(_fbb);
  builder_.add_pw(pw);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CS_LOGIN_PACKET> CreateCS_LOGIN_PACKETDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *pw = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto pw__ = pw ? _fbb.CreateString(pw) : 0;
  return FB_TABLES::CreateCS_LOGIN_PACKET(
      _fbb,
      id__,
      pw__);
}

struct SC_LOGIN_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_LOGIN_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID, 4) &&
           verifier.EndTable();
  }
};

struct SC_LOGIN_PACKETBuilder {
  typedef SC_LOGIN_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(SC_LOGIN_PACKET::VT_PLAYER_ID, player_id, 0);
  }
  explicit SC_LOGIN_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_LOGIN_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_LOGIN_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_LOGIN_PACKET> CreateSC_LOGIN_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0) {
  SC_LOGIN_PACKETBuilder builder_(_fbb);
  builder_.add_player_id(player_id);
  return builder_.Finish();
}

struct CS_ENTER_ROOM_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CS_ENTER_ROOM_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_ROOM_ID = 6
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  uint16_t room_id() const {
    return GetField<uint16_t>(VT_ROOM_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID, 4) &&
           VerifyField<uint16_t>(verifier, VT_ROOM_ID, 2) &&
           verifier.EndTable();
  }
};

struct CS_ENTER_ROOM_PACKETBuilder {
  typedef CS_ENTER_ROOM_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(CS_ENTER_ROOM_PACKET::VT_PLAYER_ID, player_id, 0);
  }
  void add_room_id(uint16_t room_id) {
    fbb_.AddElement<uint16_t>(CS_ENTER_ROOM_PACKET::VT_ROOM_ID, room_id, 0);
  }
  explicit CS_ENTER_ROOM_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CS_ENTER_ROOM_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CS_ENTER_ROOM_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CS_ENTER_ROOM_PACKET> CreateCS_ENTER_ROOM_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    uint16_t room_id = 0) {
  CS_ENTER_ROOM_PACKETBuilder builder_(_fbb);
  builder_.add_player_id(player_id);
  builder_.add_room_id(room_id);
  return builder_.Finish();
}

struct SC_ENTER_ROOM_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_ENTER_ROOM_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROOM_ID = 4
  };
  uint16_t room_id() const {
    return GetField<uint16_t>(VT_ROOM_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_ROOM_ID, 2) &&
           verifier.EndTable();
  }
};

struct SC_ENTER_ROOM_PACKETBuilder {
  typedef SC_ENTER_ROOM_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_room_id(uint16_t room_id) {
    fbb_.AddElement<uint16_t>(SC_ENTER_ROOM_PACKET::VT_ROOM_ID, room_id, 0);
  }
  explicit SC_ENTER_ROOM_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_ENTER_ROOM_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_ENTER_ROOM_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_ENTER_ROOM_PACKET> CreateSC_ENTER_ROOM_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t room_id = 0) {
  SC_ENTER_ROOM_PACKETBuilder builder_(_fbb);
  builder_.add_room_id(room_id);
  return builder_.Finish();
}

struct SC_LOCAL_PLAYER_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_LOCAL_PLAYER_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_KINEMATIC_INFO = 6,
    VT_TEAM_TYPE = 8
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  const FB_STRUCTS::KinematicInfo *kinematic_info() const {
    return GetStruct<const FB_STRUCTS::KinematicInfo *>(VT_KINEMATIC_INFO);
  }
  uint8_t team_type() const {
    return GetField<uint8_t>(VT_TEAM_TYPE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID, 4) &&
           VerifyField<FB_STRUCTS::KinematicInfo>(verifier, VT_KINEMATIC_INFO, 8) &&
           VerifyField<uint8_t>(verifier, VT_TEAM_TYPE, 1) &&
           verifier.EndTable();
  }
};

struct SC_LOCAL_PLAYER_PACKETBuilder {
  typedef SC_LOCAL_PLAYER_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(SC_LOCAL_PLAYER_PACKET::VT_PLAYER_ID, player_id, 0);
  }
  void add_kinematic_info(const FB_STRUCTS::KinematicInfo *kinematic_info) {
    fbb_.AddStruct(SC_LOCAL_PLAYER_PACKET::VT_KINEMATIC_INFO, kinematic_info);
  }
  void add_team_type(uint8_t team_type) {
    fbb_.AddElement<uint8_t>(SC_LOCAL_PLAYER_PACKET::VT_TEAM_TYPE, team_type, 0);
  }
  explicit SC_LOCAL_PLAYER_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_LOCAL_PLAYER_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_LOCAL_PLAYER_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_LOCAL_PLAYER_PACKET> CreateSC_LOCAL_PLAYER_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    const FB_STRUCTS::KinematicInfo *kinematic_info = nullptr,
    uint8_t team_type = 0) {
  SC_LOCAL_PLAYER_PACKETBuilder builder_(_fbb);
  builder_.add_kinematic_info(kinematic_info);
  builder_.add_player_id(player_id);
  builder_.add_team_type(team_type);
  return builder_.Finish();
}

struct SC_ADD_OBJ_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_ADD_OBJ_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJ_ID = 4,
    VT_OBJ_TYPE = 6,
    VT_TEAM_TYPE = 8,
    VT_NPC_TYPE = 10,
    VT_KINEMATIC_INFO = 12
  };
  uint32_t obj_id() const {
    return GetField<uint32_t>(VT_OBJ_ID, 0);
  }
  uint8_t obj_type() const {
    return GetField<uint8_t>(VT_OBJ_TYPE, 0);
  }
  uint8_t team_type() const {
    return GetField<uint8_t>(VT_TEAM_TYPE, 0);
  }
  uint8_t npc_type() const {
    return GetField<uint8_t>(VT_NPC_TYPE, 0);
  }
  const FB_STRUCTS::KinematicInfo *kinematic_info() const {
    return GetStruct<const FB_STRUCTS::KinematicInfo *>(VT_KINEMATIC_INFO);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_OBJ_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_OBJ_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_TEAM_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_NPC_TYPE, 1) &&
           VerifyField<FB_STRUCTS::KinematicInfo>(verifier, VT_KINEMATIC_INFO, 8) &&
           verifier.EndTable();
  }
};

struct SC_ADD_OBJ_PACKETBuilder {
  typedef SC_ADD_OBJ_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_obj_id(uint32_t obj_id) {
    fbb_.AddElement<uint32_t>(SC_ADD_OBJ_PACKET::VT_OBJ_ID, obj_id, 0);
  }
  void add_obj_type(uint8_t obj_type) {
    fbb_.AddElement<uint8_t>(SC_ADD_OBJ_PACKET::VT_OBJ_TYPE, obj_type, 0);
  }
  void add_team_type(uint8_t team_type) {
    fbb_.AddElement<uint8_t>(SC_ADD_OBJ_PACKET::VT_TEAM_TYPE, team_type, 0);
  }
  void add_npc_type(uint8_t npc_type) {
    fbb_.AddElement<uint8_t>(SC_ADD_OBJ_PACKET::VT_NPC_TYPE, npc_type, 0);
  }
  void add_kinematic_info(const FB_STRUCTS::KinematicInfo *kinematic_info) {
    fbb_.AddStruct(SC_ADD_OBJ_PACKET::VT_KINEMATIC_INFO, kinematic_info);
  }
  explicit SC_ADD_OBJ_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_ADD_OBJ_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_ADD_OBJ_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_ADD_OBJ_PACKET> CreateSC_ADD_OBJ_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t obj_id = 0,
    uint8_t obj_type = 0,
    uint8_t team_type = 0,
    uint8_t npc_type = 0,
    const FB_STRUCTS::KinematicInfo *kinematic_info = nullptr) {
  SC_ADD_OBJ_PACKETBuilder builder_(_fbb);
  builder_.add_kinematic_info(kinematic_info);
  builder_.add_obj_id(obj_id);
  builder_.add_npc_type(npc_type);
  builder_.add_team_type(team_type);
  builder_.add_obj_type(obj_type);
  return builder_.Finish();
}

struct SC_REMOVE_OBJ_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_REMOVE_OBJ_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJ_ID = 4
  };
  uint32_t obj_id() const {
    return GetField<uint32_t>(VT_OBJ_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_OBJ_ID, 4) &&
           verifier.EndTable();
  }
};

struct SC_REMOVE_OBJ_PACKETBuilder {
  typedef SC_REMOVE_OBJ_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_obj_id(uint32_t obj_id) {
    fbb_.AddElement<uint32_t>(SC_REMOVE_OBJ_PACKET::VT_OBJ_ID, obj_id, 0);
  }
  explicit SC_REMOVE_OBJ_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_REMOVE_OBJ_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_REMOVE_OBJ_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_REMOVE_OBJ_PACKET> CreateSC_REMOVE_OBJ_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t obj_id = 0) {
  SC_REMOVE_OBJ_PACKETBuilder builder_(_fbb);
  builder_.add_obj_id(obj_id);
  return builder_.Finish();
}

struct CS_CHAT_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CS_CHAT_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MSG = 4
  };
  const ::flatbuffers::String *msg() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MSG);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MSG) &&
           verifier.VerifyString(msg()) &&
           verifier.EndTable();
  }
};

struct CS_CHAT_PACKETBuilder {
  typedef CS_CHAT_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_msg(::flatbuffers::Offset<::flatbuffers::String> msg) {
    fbb_.AddOffset(CS_CHAT_PACKET::VT_MSG, msg);
  }
  explicit CS_CHAT_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CS_CHAT_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CS_CHAT_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CS_CHAT_PACKET> CreateCS_CHAT_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> msg = 0) {
  CS_CHAT_PACKETBuilder builder_(_fbb);
  builder_.add_msg(msg);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CS_CHAT_PACKET> CreateCS_CHAT_PACKETDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *msg = nullptr) {
  auto msg__ = msg ? _fbb.CreateString(msg) : 0;
  return FB_TABLES::CreateCS_CHAT_PACKET(
      _fbb,
      msg__);
}

struct SC_CHAT_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_CHAT_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MSG = 4
  };
  const ::flatbuffers::String *msg() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MSG);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MSG) &&
           verifier.VerifyString(msg()) &&
           verifier.EndTable();
  }
};

struct SC_CHAT_PACKETBuilder {
  typedef SC_CHAT_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_msg(::flatbuffers::Offset<::flatbuffers::String> msg) {
    fbb_.AddOffset(SC_CHAT_PACKET::VT_MSG, msg);
  }
  explicit SC_CHAT_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_CHAT_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_CHAT_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_CHAT_PACKET> CreateSC_CHAT_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> msg = 0) {
  SC_CHAT_PACKETBuilder builder_(_fbb);
  builder_.add_msg(msg);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SC_CHAT_PACKET> CreateSC_CHAT_PACKETDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *msg = nullptr) {
  auto msg__ = msg ? _fbb.CreateString(msg) : 0;
  return FB_TABLES::CreateSC_CHAT_PACKET(
      _fbb,
      msg__);
}

struct CS_MOVE_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CS_MOVE_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IS_MOVE = 4,
    VT_IS_ROTATE = 6,
    VT_KINEMATIC_INFO = 8
  };
  bool is_move() const {
    return GetField<uint8_t>(VT_IS_MOVE, 0) != 0;
  }
  bool is_rotate() const {
    return GetField<uint8_t>(VT_IS_ROTATE, 0) != 0;
  }
  const FB_STRUCTS::KinematicInfo *kinematic_info() const {
    return GetStruct<const FB_STRUCTS::KinematicInfo *>(VT_KINEMATIC_INFO);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_IS_MOVE, 1) &&
           VerifyField<uint8_t>(verifier, VT_IS_ROTATE, 1) &&
           VerifyField<FB_STRUCTS::KinematicInfo>(verifier, VT_KINEMATIC_INFO, 8) &&
           verifier.EndTable();
  }
};

struct CS_MOVE_PACKETBuilder {
  typedef CS_MOVE_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_is_move(bool is_move) {
    fbb_.AddElement<uint8_t>(CS_MOVE_PACKET::VT_IS_MOVE, static_cast<uint8_t>(is_move), 0);
  }
  void add_is_rotate(bool is_rotate) {
    fbb_.AddElement<uint8_t>(CS_MOVE_PACKET::VT_IS_ROTATE, static_cast<uint8_t>(is_rotate), 0);
  }
  void add_kinematic_info(const FB_STRUCTS::KinematicInfo *kinematic_info) {
    fbb_.AddStruct(CS_MOVE_PACKET::VT_KINEMATIC_INFO, kinematic_info);
  }
  explicit CS_MOVE_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CS_MOVE_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CS_MOVE_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CS_MOVE_PACKET> CreateCS_MOVE_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool is_move = false,
    bool is_rotate = false,
    const FB_STRUCTS::KinematicInfo *kinematic_info = nullptr) {
  CS_MOVE_PACKETBuilder builder_(_fbb);
  builder_.add_kinematic_info(kinematic_info);
  builder_.add_is_rotate(is_rotate);
  builder_.add_is_move(is_move);
  return builder_.Finish();
}

struct SC_MOVE_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_MOVE_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJ_ID = 4,
    VT_KINEMATIC_INFO = 6
  };
  uint32_t obj_id() const {
    return GetField<uint32_t>(VT_OBJ_ID, 0);
  }
  const FB_STRUCTS::KinematicInfo *kinematic_info() const {
    return GetStruct<const FB_STRUCTS::KinematicInfo *>(VT_KINEMATIC_INFO);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_OBJ_ID, 4) &&
           VerifyField<FB_STRUCTS::KinematicInfo>(verifier, VT_KINEMATIC_INFO, 8) &&
           verifier.EndTable();
  }
};

struct SC_MOVE_PACKETBuilder {
  typedef SC_MOVE_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_obj_id(uint32_t obj_id) {
    fbb_.AddElement<uint32_t>(SC_MOVE_PACKET::VT_OBJ_ID, obj_id, 0);
  }
  void add_kinematic_info(const FB_STRUCTS::KinematicInfo *kinematic_info) {
    fbb_.AddStruct(SC_MOVE_PACKET::VT_KINEMATIC_INFO, kinematic_info);
  }
  explicit SC_MOVE_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_MOVE_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_MOVE_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_MOVE_PACKET> CreateSC_MOVE_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t obj_id = 0,
    const FB_STRUCTS::KinematicInfo *kinematic_info = nullptr) {
  SC_MOVE_PACKETBuilder builder_(_fbb);
  builder_.add_kinematic_info(kinematic_info);
  builder_.add_obj_id(obj_id);
  return builder_.Finish();
}

struct CS_SUMMON_NPC FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CS_SUMMON_NPCBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct CS_SUMMON_NPCBuilder {
  typedef CS_SUMMON_NPC Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit CS_SUMMON_NPCBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CS_SUMMON_NPC> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CS_SUMMON_NPC>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CS_SUMMON_NPC> CreateCS_SUMMON_NPC(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  CS_SUMMON_NPCBuilder builder_(_fbb);
  return builder_.Finish();
}

struct CS_SOLDIER_FORMATION FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CS_SOLDIER_FORMATIONBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FORMATION = 4
  };
  uint8_t formation() const {
    return GetField<uint8_t>(VT_FORMATION, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_FORMATION, 1) &&
           verifier.EndTable();
  }
};

struct CS_SOLDIER_FORMATIONBuilder {
  typedef CS_SOLDIER_FORMATION Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_formation(uint8_t formation) {
    fbb_.AddElement<uint8_t>(CS_SOLDIER_FORMATION::VT_FORMATION, formation, 0);
  }
  explicit CS_SOLDIER_FORMATIONBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CS_SOLDIER_FORMATION> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CS_SOLDIER_FORMATION>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CS_SOLDIER_FORMATION> CreateCS_SOLDIER_FORMATION(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t formation = 0) {
  CS_SOLDIER_FORMATIONBuilder builder_(_fbb);
  builder_.add_formation(formation);
  return builder_.Finish();
}

struct CS_PLAYER_ATTACK FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CS_PLAYER_ATTACKBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct CS_PLAYER_ATTACKBuilder {
  typedef CS_PLAYER_ATTACK Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit CS_PLAYER_ATTACKBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CS_PLAYER_ATTACK> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CS_PLAYER_ATTACK>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CS_PLAYER_ATTACK> CreateCS_PLAYER_ATTACK(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  CS_PLAYER_ATTACKBuilder builder_(_fbb);
  return builder_.Finish();
}

struct SC_HIT_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_HIT_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJ_ID = 4,
    VT_CURRENT_HP = 6
  };
  uint32_t obj_id() const {
    return GetField<uint32_t>(VT_OBJ_ID, 0);
  }
  uint32_t current_hp() const {
    return GetField<uint32_t>(VT_CURRENT_HP, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_OBJ_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_CURRENT_HP, 4) &&
           verifier.EndTable();
  }
};

struct SC_HIT_PACKETBuilder {
  typedef SC_HIT_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_obj_id(uint32_t obj_id) {
    fbb_.AddElement<uint32_t>(SC_HIT_PACKET::VT_OBJ_ID, obj_id, 0);
  }
  void add_current_hp(uint32_t current_hp) {
    fbb_.AddElement<uint32_t>(SC_HIT_PACKET::VT_CURRENT_HP, current_hp, 0);
  }
  explicit SC_HIT_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_HIT_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_HIT_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_HIT_PACKET> CreateSC_HIT_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t obj_id = 0,
    uint32_t current_hp = 0) {
  SC_HIT_PACKETBuilder builder_(_fbb);
  builder_.add_current_hp(current_hp);
  builder_.add_obj_id(obj_id);
  return builder_.Finish();
}

struct CS_SOLDIER_MOVE FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CS_SOLDIER_MOVEBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POS = 4
  };
  const FB_STRUCTS::Vec3 *pos() const {
    return GetStruct<const FB_STRUCTS::Vec3 *>(VT_POS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<FB_STRUCTS::Vec3>(verifier, VT_POS, 4) &&
           verifier.EndTable();
  }
};

struct CS_SOLDIER_MOVEBuilder {
  typedef CS_SOLDIER_MOVE Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pos(const FB_STRUCTS::Vec3 *pos) {
    fbb_.AddStruct(CS_SOLDIER_MOVE::VT_POS, pos);
  }
  explicit CS_SOLDIER_MOVEBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CS_SOLDIER_MOVE> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CS_SOLDIER_MOVE>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CS_SOLDIER_MOVE> CreateCS_SOLDIER_MOVE(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const FB_STRUCTS::Vec3 *pos = nullptr) {
  CS_SOLDIER_MOVEBuilder builder_(_fbb);
  builder_.add_pos(pos);
  return builder_.Finish();
}

struct SC_REMAINING_GAME_TIME FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_REMAINING_GAME_TIMEBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REMAINING_TIME = 4
  };
  uint32_t remaining_time() const {
    return GetField<uint32_t>(VT_REMAINING_TIME, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_REMAINING_TIME, 4) &&
           verifier.EndTable();
  }
};

struct SC_REMAINING_GAME_TIMEBuilder {
  typedef SC_REMAINING_GAME_TIME Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_remaining_time(uint32_t remaining_time) {
    fbb_.AddElement<uint32_t>(SC_REMAINING_GAME_TIME::VT_REMAINING_TIME, remaining_time, 0);
  }
  explicit SC_REMAINING_GAME_TIMEBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_REMAINING_GAME_TIME> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_REMAINING_GAME_TIME>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_REMAINING_GAME_TIME> CreateSC_REMAINING_GAME_TIME(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t remaining_time = 0) {
  SC_REMAINING_GAME_TIMEBuilder builder_(_fbb);
  builder_.add_remaining_time(remaining_time);
  return builder_.Finish();
}

}  // namespace FB_TABLES

#endif  // FLATBUFFERS_GENERATED_TABLES_FB_TABLES_H_
