// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TABLES_FB_TABLES_H_
#define FLATBUFFERS_GENERATED_TABLES_FB_TABLES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "Enums_generated.h"
#include "Structs_generated.h"

namespace FB_TABLES {

struct CS_LOGIN_PACKET;
struct CS_LOGIN_PACKETBuilder;

struct CS_CHAT_PACKET;
struct CS_CHAT_PACKETBuilder;

struct CS_MOVE_PACKET_XY;
struct CS_MOVE_PACKET_XYBuilder;

struct CS_MOVE_PACKET_XYZ;
struct CS_MOVE_PACKET_XYZBuilder;

struct CS_TEST_PACKET;
struct CS_TEST_PACKETBuilder;

struct SC_CHAT_PACKET;
struct SC_CHAT_PACKETBuilder;

struct SC_MOVE_PACKET_XYZ;
struct SC_MOVE_PACKET_XYZBuilder;

struct CS_LOGIN_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CS_LOGIN_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_PW = 6
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *pw() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PW);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_PW) &&
           verifier.VerifyString(pw()) &&
           verifier.EndTable();
  }
};

struct CS_LOGIN_PACKETBuilder {
  typedef CS_LOGIN_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(CS_LOGIN_PACKET::VT_ID, id);
  }
  void add_pw(::flatbuffers::Offset<::flatbuffers::String> pw) {
    fbb_.AddOffset(CS_LOGIN_PACKET::VT_PW, pw);
  }
  explicit CS_LOGIN_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CS_LOGIN_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CS_LOGIN_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CS_LOGIN_PACKET> CreateCS_LOGIN_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> pw = 0) {
  CS_LOGIN_PACKETBuilder builder_(_fbb);
  builder_.add_pw(pw);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CS_LOGIN_PACKET> CreateCS_LOGIN_PACKETDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *pw = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto pw__ = pw ? _fbb.CreateString(pw) : 0;
  return FB_TABLES::CreateCS_LOGIN_PACKET(
      _fbb,
      id__,
      pw__);
}

struct CS_CHAT_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CS_CHAT_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MSG = 4
  };
  const ::flatbuffers::String *msg() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MSG);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MSG) &&
           verifier.VerifyString(msg()) &&
           verifier.EndTable();
  }
};

struct CS_CHAT_PACKETBuilder {
  typedef CS_CHAT_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_msg(::flatbuffers::Offset<::flatbuffers::String> msg) {
    fbb_.AddOffset(CS_CHAT_PACKET::VT_MSG, msg);
  }
  explicit CS_CHAT_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CS_CHAT_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CS_CHAT_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CS_CHAT_PACKET> CreateCS_CHAT_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> msg = 0) {
  CS_CHAT_PACKETBuilder builder_(_fbb);
  builder_.add_msg(msg);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CS_CHAT_PACKET> CreateCS_CHAT_PACKETDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *msg = nullptr) {
  auto msg__ = msg ? _fbb.CreateString(msg) : 0;
  return FB_TABLES::CreateCS_CHAT_PACKET(
      _fbb,
      msg__);
}

struct CS_MOVE_PACKET_XY FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CS_MOVE_PACKET_XYBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6
  };
  int16_t x() const {
    return GetField<int16_t>(VT_X, 0);
  }
  int16_t y() const {
    return GetField<int16_t>(VT_Y, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_X, 2) &&
           VerifyField<int16_t>(verifier, VT_Y, 2) &&
           verifier.EndTable();
  }
};

struct CS_MOVE_PACKET_XYBuilder {
  typedef CS_MOVE_PACKET_XY Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(int16_t x) {
    fbb_.AddElement<int16_t>(CS_MOVE_PACKET_XY::VT_X, x, 0);
  }
  void add_y(int16_t y) {
    fbb_.AddElement<int16_t>(CS_MOVE_PACKET_XY::VT_Y, y, 0);
  }
  explicit CS_MOVE_PACKET_XYBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CS_MOVE_PACKET_XY> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CS_MOVE_PACKET_XY>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CS_MOVE_PACKET_XY> CreateCS_MOVE_PACKET_XY(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t x = 0,
    int16_t y = 0) {
  CS_MOVE_PACKET_XYBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct CS_MOVE_PACKET_XYZ FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CS_MOVE_PACKET_XYZBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
};

struct CS_MOVE_PACKET_XYZBuilder {
  typedef CS_MOVE_PACKET_XYZ Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(CS_MOVE_PACKET_XYZ::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(CS_MOVE_PACKET_XYZ::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(CS_MOVE_PACKET_XYZ::VT_Z, z, 0.0f);
  }
  explicit CS_MOVE_PACKET_XYZBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CS_MOVE_PACKET_XYZ> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CS_MOVE_PACKET_XYZ>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CS_MOVE_PACKET_XYZ> CreateCS_MOVE_PACKET_XYZ(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  CS_MOVE_PACKET_XYZBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct CS_TEST_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CS_TEST_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
};

struct CS_TEST_PACKETBuilder {
  typedef CS_TEST_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(CS_TEST_PACKET::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(CS_TEST_PACKET::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(CS_TEST_PACKET::VT_Z, z, 0.0f);
  }
  explicit CS_TEST_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CS_TEST_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CS_TEST_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CS_TEST_PACKET> CreateCS_TEST_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  CS_TEST_PACKETBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct SC_CHAT_PACKET FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_CHAT_PACKETBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MSG = 4
  };
  const ::flatbuffers::String *msg() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MSG);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MSG) &&
           verifier.VerifyString(msg()) &&
           verifier.EndTable();
  }
};

struct SC_CHAT_PACKETBuilder {
  typedef SC_CHAT_PACKET Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_msg(::flatbuffers::Offset<::flatbuffers::String> msg) {
    fbb_.AddOffset(SC_CHAT_PACKET::VT_MSG, msg);
  }
  explicit SC_CHAT_PACKETBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_CHAT_PACKET> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_CHAT_PACKET>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_CHAT_PACKET> CreateSC_CHAT_PACKET(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> msg = 0) {
  SC_CHAT_PACKETBuilder builder_(_fbb);
  builder_.add_msg(msg);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SC_CHAT_PACKET> CreateSC_CHAT_PACKETDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *msg = nullptr) {
  auto msg__ = msg ? _fbb.CreateString(msg) : 0;
  return FB_TABLES::CreateSC_CHAT_PACKET(
      _fbb,
      msg__);
}

struct SC_MOVE_PACKET_XYZ FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_MOVE_PACKET_XYZBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
};

struct SC_MOVE_PACKET_XYZBuilder {
  typedef SC_MOVE_PACKET_XYZ Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(SC_MOVE_PACKET_XYZ::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(SC_MOVE_PACKET_XYZ::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(SC_MOVE_PACKET_XYZ::VT_Z, z, 0.0f);
  }
  explicit SC_MOVE_PACKET_XYZBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_MOVE_PACKET_XYZ> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_MOVE_PACKET_XYZ>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_MOVE_PACKET_XYZ> CreateSC_MOVE_PACKET_XYZ(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  SC_MOVE_PACKET_XYZBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

}  // namespace FB_TABLES

#endif  // FLATBUFFERS_GENERATED_TABLES_FB_TABLES_H_
