// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_STRUCTS_FB_STRUCTS_H_
#define FLATBUFFERS_GENERATED_STRUCTS_FB_STRUCTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "Enums_generated.h"

namespace FB_STRUCTS {

struct Vec3;

struct KinematicInfo;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) KinematicInfo FLATBUFFERS_FINAL_CLASS {
 private:
  FB_STRUCTS::Vec3 pos_;
  FB_STRUCTS::Vec3 rot_;
  FB_STRUCTS::Vec3 vel_;

 public:
  KinematicInfo()
      : pos_(),
        rot_(),
        vel_() {
  }
  KinematicInfo(const FB_STRUCTS::Vec3 &_pos, const FB_STRUCTS::Vec3 &_rot, const FB_STRUCTS::Vec3 &_vel)
      : pos_(_pos),
        rot_(_rot),
        vel_(_vel) {
  }
  const FB_STRUCTS::Vec3 &pos() const {
    return pos_;
  }
  const FB_STRUCTS::Vec3 &rot() const {
    return rot_;
  }
  const FB_STRUCTS::Vec3 &vel() const {
    return vel_;
  }
};
FLATBUFFERS_STRUCT_END(KinematicInfo, 36);

}  // namespace FB_STRUCTS

#endif  // FLATBUFFERS_GENERATED_STRUCTS_FB_STRUCTS_H_
