// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_STRUCTS_FB_STRUCTS_H_
#define FLATBUFFERS_GENERATED_STRUCTS_FB_STRUCTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "Enums_generated.h"

namespace FB_STRUCTS {

struct Vec3;

struct Test;

struct Vec3Test;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Test FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t player_id_;
  FB_STRUCTS::Vec3 pos_;

 public:
  Test()
      : player_id_(0),
        pos_() {
  }
  Test(uint32_t _player_id, const FB_STRUCTS::Vec3 &_pos)
      : player_id_(::flatbuffers::EndianScalar(_player_id)),
        pos_(_pos) {
  }
  uint32_t player_id() const {
    return ::flatbuffers::EndianScalar(player_id_);
  }
  const FB_STRUCTS::Vec3 &pos() const {
    return pos_;
  }
};
FLATBUFFERS_STRUCT_END(Test, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3Test FLATBUFFERS_FINAL_CLASS {
 private:
  float pos_[3];

 public:
  Vec3Test()
      : pos_() {
  }
  Vec3Test(::flatbuffers::span<const float, 3> _pos) {
    ::flatbuffers::CastToArray(pos_).CopyFromSpan(_pos);
  }
  const ::flatbuffers::Array<float, 3> *pos() const {
    return &::flatbuffers::CastToArray(pos_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3Test, 12);

}  // namespace FB_STRUCTS

#endif  // FLATBUFFERS_GENERATED_STRUCTS_FB_STRUCTS_H_
